version: '3.8'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka 
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
    - zookeeper

  omma: 
    build:
      context: ./front-end
      dockerfile: Dockerfile
    environment:
      - VITE_APP_MODE=PROD
      - VITE_PROD_AUTH=/api/auth
      - VITE_PROD_DATA=/api/data
      - VITE_PROD_MODERATION=/api/moderation
      - VITE_PROD_NOTIFICATIONS=/api/notifications
      - VITE_PROD_REGISTER=/api/register
      - VITE_PROD_SOCKET=/api/socket
    ports:
      - "5173:5173"

  auth_service:
    build:
      context: ./back-end/services/auth_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5001:5001"
    
  data_service:
    build:
      context: ./back-end/services/data_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5002:5002"

  moderation_service:
    build:
      context: ./back-end/services/moderation_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5003:5003"

  notifications_service:
    build:
      context: ./back-end/services/notifications_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5004:5004"

  register_service:
    build:
      context: ./back-end/services/register_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5005:5005"

  socket_service:
    build:
      context: ./back-end/services/socket_service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/shared:/back-end/shared
    ports:
      - "5006:5006"

  